[project]
name = "remixfy"
version = "0.1.0"
description = "Minimalistic repository-to-text package for feeding LLMs."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "requests>=2.34.2",
    "ruamel-yaml>=0.19.1",
]

[[project.authors]]
name = "Walter Dal'Maz Silva"
email = "walter.dalmazsilva@gmail.com"

[project.scripts]
repomixfy = "remixfy.repomixfy:main"
pagetree = "remixfy.pagetree:main"

[project.optional-dependencies]
test = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["src/tests"]
pythonpath = ["src"]

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
